---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: tailscale

resources:
  - operator.yaml
  - proxyclass.yaml
  - dnsconfig.yaml

images:
  - name: docker.io/tailscale/k8s-operator
    newTag: v1.94.2
