---
- name: Reload minikube-metrics
  ansible.builtin.shell: |
    launchctl unload ~/Library/LaunchAgents/mcquack.eblume.minikube-metrics.plist 2>/dev/null || true
    launchctl load ~/Library/LaunchAgents/mcquack.eblume.minikube-metrics.plist
  changed_when: true
