---
- name: reload devpi
  ansible.builtin.shell: |
    launchctl unload ~/Library/LaunchAgents/mcquack.eblume.devpi.plist 2>/dev/null || true
    launchctl load ~/Library/LaunchAgents/mcquack.eblume.devpi.plist
