apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: tailscale

resources:
  - operator.yaml
  - proxyclass.yaml
  - dnsconfig.yaml
  - egress-forge.yaml
  - external-secret.yaml
