---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: kiwix-tailscale
  namespace: kiwix
  annotations:
    tailscale.com/proxy-class: "default"
    tailscale.com/proxy-group: "ingress"
    gethomepage.dev/enabled: "true"
    gethomepage.dev/name: "Kiwix"
    gethomepage.dev/group: "Content"
    gethomepage.dev/icon: "kiwix.png"
    gethomepage.dev/description: "Offline Wikipedia"
    gethomepage.dev/href: "https://kiwix.ops.eblu.me"
    gethomepage.dev/pod-selector: "app=kiwix"
spec:
  ingressClassName: tailscale
  defaultBackend:
    service:
      name: kiwix
      port:
        number: 80
  tls:
    - hosts:
        - kiwix
