---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: kiwix-tailscale
  namespace: kiwix
  annotations:
    tailscale.com/proxy-class: "default"
    hajimari.io/enable: "true"
    hajimari.io/url: "https://kiwix.ops.eblu.me"
    hajimari.io/icon: "mdi:wikipedia"
    hajimari.io/appName: "Kiwix"
    hajimari.io/group: "Apps"
    hajimari.io/info: "Offline Wikipedia & ZIM archives"
spec:
  ingressClassName: tailscale
  defaultBackend:
    service:
      name: kiwix
      port:
        number: 80
  tls:
    - hosts:
        - kiwix
