apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: devpi-tailscale
  namespace: devpi
  annotations:
    tailscale.com/proxy-class: "default"
    tailscale.com/proxy-group: "ingress"
    gethomepage.dev/enabled: "true"
    gethomepage.dev/name: "PyPI"
    gethomepage.dev/group: "Infrastructure"
    gethomepage.dev/icon: "pypi.png"
    gethomepage.dev/description: "PyPI cache"
    gethomepage.dev/href: "https://pypi.ops.eblu.me"
    gethomepage.dev/pod-selector: "app=devpi"
spec:
  ingressClassName: tailscale
  defaultBackend:
    service:
      name: devpi
      port:
        number: 3141
  tls:
    - hosts:
        - pypi
