apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: devpi-tailscale
  namespace: devpi
  annotations:
    tailscale.com/proxy-class: "default"
    hajimari.io/enable: "true"
    hajimari.io/url: "https://pypi.ops.eblu.me"
    hajimari.io/icon: "simple-icons:pypi"
    hajimari.io/appName: "PyPI"
    hajimari.io/group: "Infrastructure"
    hajimari.io/info: "PyPI cache"
spec:
  ingressClassName: tailscale
  defaultBackend:
    service:
      name: devpi
      port:
        number: 3141
  tls:
    - hosts:
        - pypi
