apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: devpi

resources:
  - statefulset.yaml
  - service.yaml
  - ingress-tailscale.yaml
  - external-secret.yaml

images:
  - name: registry.ops.eblu.me/blumeops/devpi
    newTag: v6.19.1-ffa8727
