---
apiVersion: v1
kind: ConfigMap
metadata:
  name: docs-config
  namespace: docs
data:
  # BlumeOps docs release URL
  # Update this to deploy a new docs version
  DOCS_RELEASE_URL: "https://forge.ops.eblu.me/eblume/blumeops/releases/download/v1.0.5/docs-v1.0.5.tar.gz"
