---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: docs
resources:
  - deployment.yaml
  - service.yaml
  - ingress-tailscale.yaml
images:
  - name: registry.ops.eblu.me/blumeops/quartz
    newTag: v1.28.2-ffa8727
