apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: homepage
resources:
  - serviceaccount.yaml
  - clusterrole.yaml
  - clusterrolebinding.yaml
  - deployment.yaml
  - service.yaml
  - ingress-tailscale.yaml
  - external-secret-openweathermap.yaml
  - external-secret-jellyfin.yaml
  - external-secret-forgejo.yaml
  - external-secret-grafana.yaml
  - external-secret-miniflux.yaml
  - external-secret-navidrome.yaml

images:
  - name: registry.ops.eblu.me/blumeops/homepage
    newTag: v1.10.1-a72a0d8

configMapGenerator:
  - name: homepage-config
    files:
      - bookmarks.yaml
      - services.yaml
      - widgets.yaml
      - kubernetes.yaml
      - docker.yaml
      - settings.yaml
