---
all:
  children:
    servers:
      hosts:
        indri:
          ansible_host: indri
        ringtail:
          ansible_host: ringtail
          ansible_user: eblume
    workstations:
      hosts:
        gilbert:
          ansible_host: gilbert
    nas:
      hosts:
        sifaka:
          ansible_host: sifaka
