---
all:
  children:
    servers:
      hosts:
        indri:
          ansible_host: indri
    workstations:
      hosts:
        gilbert:
          ansible_host: gilbert
    nas:
      hosts:
        sifaka:
          ansible_host: sifaka
