---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: mqtt
resources:
  - deployment.yaml
  - service.yaml
images:
  - name: eclipse-mosquitto
    newTag: "2.0.22"
configMapGenerator:
  - name: mosquitto-config
    files:
      - mosquitto.conf
