# Tailscale Ingress for Prometheus
# Allows Alloy on indri to push metrics via remote_write
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: prometheus-tailscale
  namespace: monitoring
  annotations:
    tailscale.com/funnel: "false"
    hajimari.io/enable: "true"
    hajimari.io/url: "https://prometheus.ops.eblu.me"
    hajimari.io/icon: "simple-icons:prometheus"
    hajimari.io/appName: "Prometheus"
    hajimari.io/group: "Observability"
    hajimari.io/info: "Metrics storage"
spec:
  ingressClassName: tailscale
  rules:
    - host: prometheus
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: prometheus
                port:
                  number: 9090
  tls:
    - hosts:
        - prometheus
