apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: monitoring

resources:
  - statefulset.yaml
  - service.yaml
  - ingress-tailscale.yaml

images:
  - name: registry.ops.eblu.me/blumeops/prometheus
    newTag: v3.9.1-33b7f0f

configMapGenerator:
  - name: prometheus-config
    files:
      - prometheus.yml
