---
- name: Reload borgmatic-metrics
  ansible.builtin.shell: |
    launchctl unload ~/Library/LaunchAgents/mcquack.eblume.borgmatic-metrics.plist 2>/dev/null || true
    launchctl load ~/Library/LaunchAgents/mcquack.eblume.borgmatic-metrics.plist
  changed_when: true
