apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: teslamate-tailscale
  namespace: teslamate
  annotations:
    tailscale.com/proxy-class: "default"
    tailscale.com/proxy-group: "ingress"
    gethomepage.dev/enabled: "true"
    gethomepage.dev/name: "TeslaMate"
    gethomepage.dev/group: "Misc"
    gethomepage.dev/icon: "teslamate.png"
    gethomepage.dev/description: "Tesla data logger"
    gethomepage.dev/href: "https://tesla.ops.eblu.me"
    gethomepage.dev/pod-selector: "app=teslamate"
spec:
  ingressClassName: tailscale
  defaultBackend:
    service:
      name: teslamate
      port:
        number: 4000
  tls:
    - hosts:
        - tesla
