apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: teslamate

resources:
  - deployment.yaml
  - service.yaml
  - ingress-tailscale.yaml
  - external-secret-db.yaml
  - external-secret-encryption-key.yaml

images:
  - name: registry.ops.eblu.me/blumeops/teslamate
    newTag: v2.2.0-33b7f0f
