# ExternalSecret for Authentik database user password
#
# 1Password item: "Authentik (blumeops)" in blumeops vault
# Field: "postgresql-password"
#
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: blumeops-pg-authentik
  namespace: databases
spec:
  refreshInterval: 1h
  secretStoreRef:
    kind: ClusterSecretStore
    name: onepassword-blumeops
  target:
    name: blumeops-pg-authentik
    creationPolicy: Owner
    template:
      type: kubernetes.io/basic-auth
      data:
        username: authentik
        password: "{{ .password }}"
  data:
  - secretKey: password
    remoteRef:
      key: Authentik (blumeops)
      property: postgresql-password
