apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: databases

resources:
  - blumeops-pg.yaml
  - immich-pg.yaml
  - service-tailscale.yaml
  - service-metrics-tailscale.yaml
  - external-secret-eblume.yaml
  - external-secret-borgmatic.yaml
  - external-secret-teslamate.yaml
  - external-secret-authentik.yaml
