# Tailscale Ingress for ArgoCD
# Exposes ArgoCD at https://argocd.tail8d86e.ts.net with Let's Encrypt TLS
#
# Using Ingress instead of LoadBalancer to get automatic TLS certificates.
# See: https://tailscale.com/kb/1439/kubernetes-operator-cluster-ingress
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: argocd-server-tailscale
  namespace: argocd
  annotations:
    tailscale.com/proxy-class: "default"
    tailscale.com/proxy-group: "ingress"
    gethomepage.dev/enabled: "true"
    gethomepage.dev/name: "ArgoCD"
    gethomepage.dev/group: "Misc"
    gethomepage.dev/icon: "argo-cd.png"
    gethomepage.dev/description: "GitOps CD"
    gethomepage.dev/href: "https://argocd.ops.eblu.me"
    gethomepage.dev/pod-selector: "app.kubernetes.io/name=argocd-server"
spec:
  ingressClassName: tailscale
  defaultBackend:
    service:
      name: argocd-server
      port:
        number: 80
  tls:
    - hosts:
        - argocd
