apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: argocd

resources:
  # Pin to specific version for intentional upgrades
  - https://raw.githubusercontent.com/argoproj/argo-cd/v3.2.6/manifests/install.yaml
  - ingress-tailscale.yaml
  - external-secret-repo-forge.yaml

patches:
  - path: argocd-cmd-params-cm.yaml
  - path: argocd-ssh-known-hosts-cm.yaml
  - path: argocd-cm-patch.yaml
  - path: argocd-rbac-cm-patch.yaml
