# Tailscale Ingress for ArgoCD
# Exposes ArgoCD at https://argocd.tail8d86e.ts.net with Let's Encrypt TLS
#
# Using Ingress instead of LoadBalancer to get automatic TLS certificates.
# See: https://tailscale.com/kb/1439/kubernetes-operator-cluster-ingress
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: argocd-server-tailscale
  namespace: argocd
  annotations:
    tailscale.com/proxy-class: "default"
    hajimari.io/enable: "true"
    hajimari.io/url: "https://argocd.ops.eblu.me"
    hajimari.io/icon: "simple-icons:argo"
    hajimari.io/appName: "ArgoCD"
    hajimari.io/group: "Infrastructure"
    hajimari.io/info: "GitOps CD"
spec:
  ingressClassName: tailscale
  defaultBackend:
    service:
      name: argocd-server
      port:
        number: 80
  tls:
    - hosts:
        - argocd
