apiVersion: v1
kind: ConfigMap
metadata:
  name: grafana
  namespace: monitoring
  labels:
    app.kubernetes.io/name: grafana
    app.kubernetes.io/instance: grafana
data:
  grafana.ini: |
    [analytics]
    check_for_updates = false
    reporting_enabled = false

    [auth.generic_oauth]
    allow_sign_up = true
    api_url = https://authentik.ops.eblu.me/application/o/userinfo/
    auth_url = https://authentik.ops.eblu.me/application/o/authorize/
    auto_login = false
    client_id = grafana
    client_secret = $__env{GF_AUTH_GENERIC_OAUTH_CLIENT_SECRET}
    enabled = true
    name = Authentik
    role_attribute_path = contains(groups[*], 'admins') && 'Admin' || 'Viewer'
    skip_org_role_sync = false
    scopes = openid profile email
    token_url = https://authentik.ops.eblu.me/application/o/token/

    [log]
    mode = console

    [paths]
    data = /var/lib/grafana/
    logs = /var/log/grafana
    plugins = /var/lib/grafana/plugins
    provisioning = /etc/grafana/provisioning

    [security]
    allow_embedding = false

    [server]
    root_url = https://grafana.ops.eblu.me

  datasources.yaml: |
    apiVersion: 1
    datasources:
    - access: proxy
      editable: false
      isDefault: true
      name: Prometheus
      orgId: 1
      type: prometheus
      uid: prometheus
      url: http://prometheus.monitoring.svc.cluster.local:9090
    - access: proxy
      editable: false
      name: Loki
      orgId: 1
      type: loki
      uid: loki
      url: http://loki.monitoring.svc.cluster.local:3100
    - access: proxy
      database: teslamate
      editable: false
      jsonData:
        connMaxLifetime: 14400
        maxIdleConns: 2
        maxOpenConns: 5
        sslmode: disable
      name: TeslaMate
      orgId: 1
      secureJsonData:
        password: $TESLAMATE_DB_PASSWORD
      type: postgres
      uid: TeslaMate
      url: blumeops-pg-rw.databases.svc.cluster.local:5432
      user: teslamate
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: grafana-config-dashboards
  namespace: monitoring
  labels:
    app.kubernetes.io/name: grafana
    app.kubernetes.io/instance: grafana
data:
  provider.yaml: |
    apiVersion: 1
    providers:
      - name: 'sidecarProvider'
        orgId: 1
        type: file
        disableDeletion: false
        allowUiUpdates: false
        updateIntervalSeconds: 30
        options:
          foldersFromFilesStructure: true
          path: /tmp/dashboards
