---
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: authentik-config
  namespace: authentik
spec:
  refreshInterval: 1h
  secretStoreRef:
    kind: ClusterSecretStore
    name: onepassword-blumeops
  target:
    name: authentik-config
    creationPolicy: Owner
  data:
    - secretKey: secret-key
      remoteRef:
        key: "Authentik (blumeops)"
        property: secret-key
    - secretKey: postgresql-host
      remoteRef:
        key: "Authentik (blumeops)"
        property: postgresql-host
    - secretKey: postgresql-port
      remoteRef:
        key: "Authentik (blumeops)"
        property: postgresql-port
    - secretKey: postgresql-name
      remoteRef:
        key: "Authentik (blumeops)"
        property: postgresql-name
    - secretKey: postgresql-user
      remoteRef:
        key: "Authentik (blumeops)"
        property: postgresql-user
    - secretKey: postgresql-password
      remoteRef:
        key: "Authentik (blumeops)"
        property: postgresql-password
    - secretKey: grafana-client-secret
      remoteRef:
        key: "Authentik (blumeops)"
        property: grafana-client-secret
    - secretKey: forgejo-client-secret
      remoteRef:
        key: "Authentik (blumeops)"
        property: forgejo-client-secret
    - secretKey: zot-client-secret
      remoteRef:
        key: "Authentik (blumeops)"
        property: zot-client-secret
