---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: authentik
resources:
  - external-secret.yaml
  - configmap-blueprint.yaml
  - deployment-server.yaml
  - deployment-worker.yaml
  - deployment-redis.yaml
  - service.yaml
  - service-redis.yaml
  - ingress-tailscale.yaml
images:
  - name: registry.ops.eblu.me/blumeops/authentik
    newTag: v2026.2.0-2d4098e-nix
  - name: docker.io/library/redis
    newTag: 7-alpine
