---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: authentik
resources:
  - external-secret.yaml
  - deployment-server.yaml
  - deployment-worker.yaml
  - deployment-redis.yaml
  - service.yaml
  - service-redis.yaml
  - ingress-tailscale.yaml
