apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: alloy

resources:
  - namespace.yaml
  - rbac.yaml
  - daemonset.yaml

images:
  - name: grafana/alloy
    newTag: v1.13.1

configMapGenerator:
  - name: alloy-config
    files:
      - config.alloy
