---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: transmission-tailscale
  namespace: torrent
  annotations:
    tailscale.com/proxy-class: "default"
    tailscale.com/proxy-group: "ingress"
    gethomepage.dev/enabled: "true"
    gethomepage.dev/name: "Transmission"
    gethomepage.dev/group: "Misc"
    gethomepage.dev/icon: "transmission.png"
    gethomepage.dev/description: "Torrent client"
    gethomepage.dev/href: "https://torrent.ops.eblu.me"
    gethomepage.dev/pod-selector: "app=transmission"
    # TODO: Add Transmission widget - requires username/password setup in Transmission
    # See: https://gethomepage.dev/widgets/services/transmission/
    # gethomepage.dev/widget.type: "transmission"
    # gethomepage.dev/widget.url: "https://torrent.ops.eblu.me"
    # gethomepage.dev/widget.username: "{{HOMEPAGE_VAR_TRANSMISSION_USER}}"
    # gethomepage.dev/widget.password: "{{HOMEPAGE_VAR_TRANSMISSION_PASSWORD}}"
spec:
  ingressClassName: tailscale
  defaultBackend:
    service:
      name: transmission
      port:
        number: 9091
  tls:
    - hosts:
        - torrent
