---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: transmission-tailscale
  namespace: torrent
  annotations:
    tailscale.com/proxy-class: "default"
    gethomepage.dev/enabled: "true"
    gethomepage.dev/name: "Transmission"
    gethomepage.dev/group: "Apps"
    gethomepage.dev/icon: "transmission.png"
    gethomepage.dev/description: "Torrent client"
    gethomepage.dev/href: "https://torrent.ops.eblu.me"
    gethomepage.dev/pod-selector: "app=transmission"
spec:
  ingressClassName: tailscale
  defaultBackend:
    service:
      name: transmission
      port:
        number: 9091
  tls:
    - hosts:
        - torrent
