---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: torrent
resources:
  - pv-nfs.yaml
  - pvc.yaml
  - deployment.yaml
  - service.yaml
  - ingress-tailscale.yaml
images:
  - name: registry.ops.eblu.me/blumeops/transmission
    newTag: v4.0.6-r4-ffa8727
