---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: navidrome-tailscale
  namespace: navidrome
  annotations:
    tailscale.com/proxy-class: "default"
    tailscale.com/proxy-group: "ingress"
    gethomepage.dev/enabled: "true"
    gethomepage.dev/name: "DJ"
    gethomepage.dev/group: "Content"
    gethomepage.dev/icon: "navidrome.png"
    gethomepage.dev/description: "Music streaming server"
    gethomepage.dev/href: "https://dj.ops.eblu.me"
    gethomepage.dev/pod-selector: "app=navidrome"
    gethomepage.dev/widget.type: "navidrome"
    gethomepage.dev/widget.url: "https://dj.ops.eblu.me"
    gethomepage.dev/widget.user: "{{HOMEPAGE_VAR_NAVIDROME_USER}}"
    gethomepage.dev/widget.token: "{{HOMEPAGE_VAR_NAVIDROME_TOKEN}}"
    gethomepage.dev/widget.salt: "{{HOMEPAGE_VAR_NAVIDROME_SALT}}"
spec:
  ingressClassName: tailscale
  defaultBackend:
    service:
      name: navidrome
      port:
        number: 4533
  tls:
    - hosts:
        - dj
