---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: navidrome
resources:
  - pv-nfs.yaml
  - pvc-music.yaml
  - pvc-data.yaml
  - deployment.yaml
  - service.yaml
  - ingress-tailscale.yaml
images:
  - name: registry.ops.eblu.me/blumeops/navidrome
    newTag: v0.60.3-a72a0d8
