---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: navidrome
resources:
  - pv-nfs.yaml
  - pvc-music.yaml
  - pvc-data.yaml
  - deployment.yaml
  - service.yaml
  - ingress-tailscale.yaml
