---
- name: reload transmission-metrics
  ansible.builtin.shell: |
    launchctl unload ~/Library/LaunchAgents/mcquack.eblume.transmission-metrics.plist 2>/dev/null || true
    launchctl load ~/Library/LaunchAgents/mcquack.eblume.transmission-metrics.plist
