---
borgmatic_metrics_repo: /Volumes/backups/borg/
borgmatic_metrics_passcommand: cat /Users/erichblume/.borg/config.yaml
borgmatic_metrics_dir: /opt/homebrew/var/node_exporter/textfile
borgmatic_metrics_script: /Users/erichblume/.local/bin/borgmatic-metrics
borgmatic_metrics_interval: 3600  # seconds between metric collection (hourly)
borgmatic_metrics_log_dir: /opt/homebrew/var/log
