---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: ntfy-tailscale
  namespace: ntfy
  annotations:
    tailscale.com/proxy-class: "default"
    tailscale.com/proxy-group: "ingress"
    gethomepage.dev/enabled: "true"
    gethomepage.dev/name: "Ntfy"
    gethomepage.dev/group: "Infrastructure"
    gethomepage.dev/icon: "ntfy.png"
    gethomepage.dev/description: "Push notifications"
    gethomepage.dev/href: "https://ntfy.ops.eblu.me"
    gethomepage.dev/pod-selector: "app=ntfy"
spec:
  ingressClassName: tailscale
  defaultBackend:
    service:
      name: ntfy
      port:
        number: 80
  tls:
    - hosts:
        - ntfy
