---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: ntfy
resources:
  - deployment.yaml
  - service.yaml
  - ingress-tailscale.yaml
images:
  - name: registry.ops.eblu.me/blumeops/ntfy
    newTag: v2.17.0-cd57814-nix
configMapGenerator:
  - name: ntfy-config
    files:
      - server.yml
