apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: monitoring

resources:
  - statefulset.yaml
  - service.yaml
  - ingress-tailscale.yaml

images:
  - name: grafana/loki
    newTag: "3.6.5"

configMapGenerator:
  - name: loki-config
    files:
      - loki-config.yaml
