apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: nvidia-device-plugin

resources:
  - daemonset.yaml
  - runtime-class.yaml

images:
  - name: nvcr.io/nvidia/k8s-device-plugin
    newTag: v0.18.2
