---
- name: Reload borgmatic
  ansible.builtin.shell: |
    launchctl unload ~/Library/LaunchAgents/mcquack.eblume.borgmatic.plist 2>/dev/null || true
    launchctl load ~/Library/LaunchAgents/mcquack.eblume.borgmatic.plist
  changed_when: true
