apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: frigate-camera
  namespace: frigate
spec:
  refreshInterval: 1h
  secretStoreRef:
    kind: ClusterSecretStore
    name: onepassword-blumeops
  target:
    name: frigate-camera
    creationPolicy: Owner
  data:
    - secretKey: username
      remoteRef:
        key: Reolink Floodlight Camera
        property: username
    - secretKey: password
      remoteRef:
        key: Reolink Floodlight Camera
        property: password
