---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: frigate-tailscale
  namespace: frigate
  annotations:
    tailscale.com/proxy-class: "default"
    tailscale.com/proxy-group: "ingress"
    gethomepage.dev/enabled: "true"
    gethomepage.dev/name: "NVR"
    gethomepage.dev/group: "Infrastructure"
    gethomepage.dev/icon: "frigate.png"
    gethomepage.dev/description: "Network video recorder"
    gethomepage.dev/href: "https://nvr.ops.eblu.me"
    gethomepage.dev/pod-selector: "app=frigate"
spec:
  ingressClassName: tailscale
  defaultBackend:
    service:
      name: frigate
      port:
        number: 5000
  tls:
    - hosts:
        - nvr
