---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: frigate
resources:
  - external-secret.yaml
  - configmap.yaml
  - configmap-notify.yaml
  - pv-nfs.yaml
  - pvc-recordings.yaml
  - pvc-database.yaml
  - deployment.yaml
  - deployment-notify.yaml
  - service.yaml
  - ingress-tailscale.yaml
