---
- name: Restart alloy
  ansible.builtin.shell: |
    launchctl unload ~/Library/LaunchAgents/mcquack.eblume.alloy.plist 2>/dev/null || true
    launchctl load ~/Library/LaunchAgents/mcquack.eblume.alloy.plist
  changed_when: true
