apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: miniflux-tailscale
  namespace: miniflux
  annotations:
    tailscale.com/proxy-class: "crio-compat"
spec:
  ingressClassName: tailscale
  defaultBackend:
    service:
      name: miniflux
      port:
        number: 8080
  tls:
    - hosts:
        - feed
