apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: miniflux-tailscale
  namespace: miniflux
  annotations:
    tailscale.com/proxy-class: "default"
    hajimari.io/enable: "true"
    hajimari.io/url: "https://feed.ops.eblu.me"
    hajimari.io/icon: "mdi:rss"
    hajimari.io/appName: "Miniflux"
    hajimari.io/group: "Apps"
    hajimari.io/info: "RSS reader"
spec:
  ingressClassName: tailscale
  defaultBackend:
    service:
      name: miniflux
      port:
        number: 8080
  tls:
    - hosts:
        - feed
