---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: cv
resources:
  - deployment.yaml
  - service.yaml
  - ingress-tailscale.yaml
images:
  - name: registry.ops.eblu.me/blumeops/cv
    newTag: v1.0.3-ffa8727
